name: Generate training data
on:
  push:
    branches:
     - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install --upgrade setuptools wheel

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Orchestrate
        run: cd data && python3 -u aggregation.py
